version: "3.8"

services:
  app:
    image: fastapi-app-sprocket-image
    container_name: fastapi-app-sprocket-container
    environment:
      - DEBUG=True
    volumes:
      - ../../.:/app/.
    ports:
      - 8000:8000
    build:
      context: ../../
      dockerfile: setup/docker/Dockerfile
#    command: python start_server.py
    command: tail -f /dev/null
    depends_on:
      - database-app-container
    networks:
      sprocketnetwork:
        aliases:
          - app-container

  database-app-container:
    image: postgres:14.4
    container_name: database-app-container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: fastapi
    networks:
      sprocketnetwork:
        aliases:
          - app-database
    ports:
      - 5432:5432

volumes:
  postgres_data:

networks:
  sprocketnetwork:
    external: true
