name: Testing fastapi

on:
  pull_request:

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md"]'
  pytest:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -U pip
          pip install poetry==1.4.2
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Setup GIT
        run: |
          git config --global user.name "fastapi"
          git config --global user.email "fastapi@pytest.python"
      - name: Run tests
        run: pytest
